### ISSUE TITLE
Landing Page not displaying Properly on Safari

### ISSUE THREAD

**Issue by BolajiOlajide** [find-treasure-app/public#1]
# Bug Description

When I try to access the landing page on Safari, the header doesn't display. All I get is a blank page.

## URL

I experienced the bug on [this URL](https://findtreasure.app).

## Reproduction Steps

Steps to reproduce the behaviour:

1. Go to [this URL](https://findtreasure.app)
## Expected Behaviour

I should see a header and a sub-header with the text:

```
Find Treasure App
Write code and call APIs to win actual money
```

**Screenshots**

- Screenshot 1
<img width="1782" alt="Screenshot 2020-07-30 at 17 21 20" src="https://user-images.githubusercontent.com/25608335/88947928-2917ce80-d289-11ea-9a1a-87700568ecba.png">

- Screenshot 2

**Platform (please complete the following information):**

- Screen: Desktop
- OS: macOS
- Browser: Safari
- Version: 13.1.1

## Additional context

N/A

**Comment by BolajiOlajide** [comment]
Hello @mykeels 

This is working fine now.
<img width="1736" alt="Screenshot 2020-08-03 at 01 30 36" src="https://user-images.githubusercontent.com/25608335/89135951-f986f180-d528-11ea-866f-4cd98b321906.png">

**Comment by mykeels** [comment]
Awesome. Closing.
